services:
  mlflow-lab:
    build: .
    container_name: mlflow-lab
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-lab:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio-mlflow-lab:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    ports:
      - "5000:5000"
    depends_on:
      - postgres-mlflow-lab
      - minio-mlflow-lab
    command: >
      mlflow server
        --host 0.0.0.0
        --backend-store-uri postgresql://postgres:postgres@postgres-mlflow-lab/mlflowdb
        --default-artifact-root s3://mlflow-lab/

  postgres-mlflow-lab:
    image: postgres:latest
    container_name: postgres-mlflow-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlflowdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio-mlflow-lab:
    image: minio/minio:latest
    container_name: minio-mlflow-lab
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
